################################################################################
# Passwords
#
# App 1 — generated by Terraform, stored in Secrets Manager.
#   The module writes this password into /etc/redis/redis.conf automatically
#   via user_data at launch time. App 1's runtime code can fetch the password
#   from Secrets Manager without any manual steps.
#
# App 2+ — generated by Terraform for convenience only.
#   NOT stored in Secrets Manager. The operator retrieves the password with:
#     terraform output -raw app2_redis_password
#   and passes it to the deploy script (scripts/01_deploy_app2.sh).
#   App 2's setup is a manual post-deploy step, so there is no value in
#   automating secret storage for it.
#
# special = false avoids shell-quoting issues when the password is substituted
# into redis.conf by the deploy script using a heredoc.
################################################################################

resource "random_password" "app1_redis" {
  length  = 32
  special = false
}

resource "random_password" "app2_redis" {
  length  = 32
  special = false
}

# Secrets Manager — App 1 only
resource "aws_secretsmanager_secret" "app1_redis" {
  name                    = "${var.env}-${var.project_id}-app1-redis-password"
  recovery_window_in_days = 7
}

resource "aws_secretsmanager_secret_version" "app1_redis" {
  secret_id     = aws_secretsmanager_secret.app1_redis.id
  secret_string = random_password.app1_redis.result
}
