################################################################################
# Snippet for adding one more app to the shared Redis host.
#
# This file is written as App 3 (port 6381). To add App 4, App 5, … :
#   - Find-and-replace "app3" → "app4", "6381" → "6382", etc.
#   - Add the matching variable to variables.tf (see bottom of this file)
#
# Port reference:
#   App 3 → 6381   App 4 → 6382   App 5 → 6383   App 6 → 6384  …
################################################################################

# Step 1 — declare the input variable (add this to terraform/variables.tf)
variable "app3_security_group_id" {
  description = "Security group of App 3 compute resources (ECS tasks, EC2, Lambda, etc.)"
  type        = string
}

# Step 2 — password (generated by Terraform, NOT stored in Secrets Manager)
resource "random_password" "app3_redis" {
  length  = 32
  special = false
}

# Step 3 — security group ingress (only App 3's SG can reach port 6381)
resource "aws_security_group_rule" "app3_redis_ingress" {
  type                     = "ingress"
  from_port                = 6381
  to_port                  = 6381
  protocol                 = "tcp"
  source_security_group_id = var.app3_security_group_id
  security_group_id        = module.redis_host.redis.security_group.id
  description              = "App 3 Redis (port 6381)"
}

# Step 4 — outputs
output "app3_redis_connection" {
  description = "Non-sensitive App 3 connection values — copy directly into .env"
  value = {
    REDIS_HOST              = module.redis_host.redis.connection.host
    REDIS_PORT              = "6381"
    REDIS_DB                = "0"
    REDIS_CACHE_DB          = "1"
    REDIS_SESSION_DB        = "2"
    REDIS_QUEUE_DB          = "3"
    REDIS_HORIZON_DB        = "4"
    REDIS_SCHEDULER_LOCK_DB = "5"
  }
}

output "app3_redis_password" {
  description = "App 3 Redis password — pass to scripts/deploy_appN.sh"
  value       = random_password.app3_redis.result
  sensitive   = true
}
